"""empty message

Revision ID: 6811e1484a77
Revises: 9b39c303eacc
Create Date: 2023-07-27 21:18:36.442939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6811e1484a77'
down_revision = '9b39c303eacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Empresas', sa.Column('nome_fantasia', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Empresas', 'nome_fantasia')
    # ### end Alembic commands ###
