"""empty message

Revision ID: 9b39c303eacc
Revises: 0a4f7e1be8f2
Create Date: 2023-07-26 21:51:04.711959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b39c303eacc'
down_revision = '0a4f7e1be8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('acess_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'acess_level')
    # ### end Alembic commands ###
